FROM caddy:alpine

# GIT
RUN apk add --no-cache git

# SUPPRESSION ANCIEN HTML
RUN rm -rf /usr/share/caddy/*

# CLONE /usr/share/caddy
RUN git clone https://github.com/withaarzoo/3D-Rotate-Tube.git /usr/share/caddy

# PORT 80
EXPOSE 80